### PR TITLE
Improve path handling and control over intermediate files

### LINKED ISSUE #29: Don't use absolute paths or `output_dir` when rendering from Rmd
It's a bit of a quirk of `rmarkdown::render()`, but using an absolute path in `output_file` or using `output_dir` can cause problems that are often not easily apparent until working in an environment where relative paths are required. In particular, using either of the above will cause `rmarkdown::render()` to write figure outputs using absolute file paths. This becomes an issue when an HTML file is served to a browser where the paths need to be relative.

Here's a reprex that demonstrates the issue:

``` r
# disable the imgur uploading in {reprex}
knitr::opts_knit$set("upload.fun" = identity)

library(xaringanBuilder)

# A minimal slide document with a single plot
cat(
  "---",
  "output: xaringan::moon_reader",
  "---",
  "",
  "```{r}",
  "plot(faithful)",
  "```",
  sep = "\n",
  file = "demo.Rmd"
)

build_pdf("demo.Rmd")
#> ℹ Building demo.html from demo.Rmd
#> ℹ Building demo.pdf from demo.html
#> Error in force(expr): Failed to generate output. Reason: Failed to open http://127.0.0.1:7737/private/var/folders/zw/8z2vpz1s0cl3gwpyh5p72mwh0000gn/T/Rtmp3nVWkK/reprex-2a9138331d3c-fussy-agama/demo_files/figure-html/unnamed-chunk-3-1.png (HTTP status code: 404)
#> ✓ Building demo.pdf from demo.html ... done
#> 
#> ℹ Building demo.html from demo.Rmd✓ Building demo.html from demo.Rmd ... done

html <- readLines("demo.html")

grep("figure-html", html, value = TRUE)
#> [1] "![](/private/var/folders/zw/8z2vpz1s0cl3gwpyh5p72mwh0000gn/T/Rtmp3nVWkK/reprex-2a9138331d3c-fussy-agama/demo_files/figure-html/unnamed-chunk-3-1.png)&lt;!-- --&gt;"
```

The image link points to the full absolute file path of the the rendered plot, but the absolute path can't be found once the page is being served to a browser. (Notice the link starts with `/private/var/...`.)

Instead we need the relative URL, e.g. `demo_fies/figure-html/unnamed-chunk-3-1.png`.

If we need to be able to support rendering the HTML with an output file in a different folder, it's best to move into the folder containing `input.Rmd`, render the file to a temporary file (in that folder), and then move the temp file to a new folder. Except in the case of xaringan, this is likely to fail without a bunch more work, unless the slides are `self_contained: true`.

In light of the above, I'd recommend temporarily moving into the directory containing the input file before calling `rmarkdown::render()` and giving just the `basename(output_file)` to the `output_file` argument.

### LINKED ISSUE #30: Provide user control over overwriting behavior
I would appreciate it if there were a way to have a little more control over the overwriting behavior of the `build_*()` functions. Currently, files are overwritten without any warning or confirmation and there's no way to turn that feature off. This always makes me nervous, especially when it's possible to call a `build_*()` function from the wrong directory and create unexpected files that unintentionally overwrite files in the wrong location.

It'd be good to at minimum have a way to set `overwrite = FALSE` even if the default value were `TRUE` for ergonomic reasons.

### PR DESCRIPTION
**Pull request by gadenbuie**
## Overview

Here are the notes I added to the NEWS file, which provide a decent summary of this PR.

* Added a new argument `keep_intermediates` to all `build_*()` functions downstream from `build_html()`. When `FALSE`, intermediate files required to build the final output are removed when the output is produced.

* Improved internal handling of file paths when the input and output files have different base names and directories. Fixes #30

* `build_html()` gains `self_contained` and `rmd_args` arguments that are passed to `rmarkdown::render()` and can be used to override the options in the YAML header of the slides document.

* `build_html()` now sets `self_contained = TRUE` automatically when the output `.html` file won't be saved to the same directory as the input `.Rmd`. Fixes #29

* The `slides` argument now accepts `"all"`, `"first"`, or `"last"` to build the first, last or all slides. `slides` also accepts negative slide indices to exclude slides, e.g. `-1:-3` excludes the first three slides.

* Dependencies that are used for only one type of output were made suggested dependencies to improve the installation experience for the majority of users. Install `xaringanBuilder` with `dependencies = TRUE` for full installation.

## Details

The biggest change is the new flow around the function `path_from()`. There are three primary features it provides.

First, `path_from()` takes an path and an expected xaringanBuilder output type and returns a new path based on the input, but with the correct name and extension. In this way it’s similar to `build_paths()` but the transformation is done on the fly. (Note that it always returns absolute paths and I ran this with `reprex` so I cleaned up the paths a little bit.)

``` r
path_from("slides.Rmd", "html")
#> /reprexfb8b3b242eaf/slides.html
path_from("example/slides.pdf", "mp4")
#> /reprexfb8b3b242eaf/example/slides.mp4
path_from("slides.html", "url")
#> [1] "file:///reprexfb8b3b242eaf/slides.html"
path_from("https://example.com/slides", "pdf")
#> Warning in path_from("https://example.com/slides", "pdf"): No `dir` provided,
#> using working directory.
#> [1] /reprexfb8b3b242eaf/slides.pdf
```

Second, it can be used to create *temporary* file paths. When `temporary = TRUE`, we use `withr::defer()` to remove the temp file whenever the calling function exits. So if a temporary file is created inside, e.g. `build_pdf()`, for the HTML file, when `build_pdf()` exists the `.html` file is thrown away. The temporary file has a consistent file name so that they’re easy to find if anything goes wrong, and `path_from()` doesn’t automatically create the file, just the file path. Nothing bad happens if no file exists when the clean-up process runs.

``` r
local({
    tmpfile <- path_from("slides.Rmd", "html", temporary = TRUE)
    fs::file_create(tmpfile)
})
#> ℹ Removed temporary 'xaringanBuilder_1304a23a3021e.html'
```

Finally, the new flow with `path_from()` is to only use `input` when `output_file` is `NULL` and then thereafter to build files paths from the output. For example, if we need to create a PDF file but we were given the `.Rmd`…

``` r
input <- "slides.Rmd"

# assume output_file was NULL, so we need the default
output_file <- path_from(input, "pdf")
output_file
#> /reprexfb8b7770931a/slides.pdf

step_html <- path_from(output_file, "html", temporary = TRUE)
step_html
#> /reprexfb8b7770931a/xaringanBuilder_130df4fcae623.html
```

Alternatively, if we *do* have an `output_file`, we end up choosing the right folder for the output files by always using the `output_file` to construct intermediate paths.

``` r
input <- "slides.Rmd"
output_file <- "../slides.pdf"

step_html <- path_from(output_file, "html", temporary = TRUE)
step_html
#> /xaringanBuilder_1304a18f85831.html
```

### CODE REVIEW

**Comment by jhelvy** [comment]
Hooray for adding the tests! That has been sorely needed for quite a while.

Were you also going to add the `keep_intermediates` argument to all `build_*()` functions from pdf and later in the build hierarchy? Or just to `build_pdf()`? I imagine fewer people will want the intermediates for anything beyond the PDF, but it'd be nice to allow them to do so if they wanted. Could just make the default value `FALSE` for those functions.

**Comment by gadenbuie** [comment]
Thanks! And yes, I'm working my way through the functions to use the new `path_from()` flow (rather than

**Comment by gadenbuie** [comment]
Thanks! And yes, I'm working my way through the functions to use the new `path_from()` flow (rather than building the paths all at once). I've got `build_html()` and `build_pdf()`set up, but I have a little more work to do to convince myself that `build_html()` is making the best decisions wrt paths. Then I'll update the other build functions too. I made the draft PR so we don't end up duplicating work -- feel free to leave comments any time or to wait for the final PR if you'd prefer.

**Comment by jhelvy** [comment]
I didn't even know you could make a draft PR lol. This is a really nice workflow! I'm watching the kids all day, so I might be able to take a closer look later tonight. But in general dynamically creating the paths seems like a much better approach. My simple `build_paths()` served well back when the build hierarchy was simpler, but now it's creating new problems.

**Comment by jhelvy** [comment]
Okay noticed a couple things in `build_html()`:

- Did you mean to use `path_from()` on [line 25](https://github.com/gadenbuie/xaringanBuilder/blob/simplify-path-handling/R/html.R#L25) instead of `path_new()`?
- I would expect that if the user doesn't provide an `output_file`, then the function should build the output to the same directory using the same file name as `input`, but with the appropriate extension (e.g., that's how I've set up some of the [examples](https://github.com/jhelvy/xaringanBuilder/blob/master/inst/example/examples.R)). The `assert_path_ext()` on [line 21](https://github.com/gadenbuie/xaringanBuilder/blob/simplify-path-handling/R/html.R#L21) will throw an error if `output_file = NULL`, which is the default value.  In the previous [`assert_io_paths()` function](https://github.com/jhelvy/xaringanBuilder/blob/master/R/utils.R#L1), there was an if statement such that the path extension would only be checked if `! is.null(output_file))`. I think you just need to add that condition to [line 3](https://github.com/gadenbuie/xaringanBuilder/blob/simplify-path-handling/R/utils.R#L3)

**Comment by gadenbuie** [comment]
> * Did you mean to use `path_from()` on [line 25](https://github.com/gadenbuie/xaringanBuilder/blob/simplify-path-handling/R/html.R?rgh-link-date=2021-07-18T00%3A53%3A14Z#L25) instead of `path_new()`?

Yes definitely! Thanks for catching that (and also that's why I like writing tests 😄)

> * I would expect that if the user doesn't provide an `output_file`, then the function should build the output to the same directory using the same file name as `input`, but with the appropriate extension

Yes, that's also the plan! I fixed that as well, but by filling in `output_file` before checking the path extension. That way we keep the behavior (using the `input` filename and directory with the updated extension) but we have a strong check that the file extensions are correct before we go build things.

**Review by jhelvy — COMMENTED** [review]
Thanks for making the `slides` argument more robust! 🤘

Since you're on this, how do you like the name `slides` for this argument? It's not 100% clear what it does based on the name, but I never came up with anything better. It's also a little odd to me to get all the slides when `slides = NULL`. It's more like a *subset* of slides, which makes more sense to get all the slides if *subset* = NULL. Anyway, it's not a critical thing as the documentation is pretty clear, but I always try and come up with as intuitive argument names as possible.

**Comment by jhelvy** [comment]
Go @gadenbuie go! So many improvements in this PR! I've been following along, but I'm mostly just sitting on the sidelines cheering 🎉   (and also learning new things...I never knew about `@inheritParams` - that is such a nice feature).

**Comment by gadenbuie** [comment]
Thanks @jhelvy! I think this is pretty much ready to go! I'll try to summarize the changes this evening and then remove the draft label. While I'm working on the test suite would you like to have CI checking with GitHub actions? I think I could set it up fairly easily if that's something you're interested in.

**Comment by jhelvy** [comment]
You mean an additional action to run like R CMD check on every commit? Something like that could be useful to catch errors. I usually run it locally anyway but it could be helpful in case you accidentally commit a file or change that breaks something.

**Review by jhelvy — COMMENTED** [review]
I originally had `slides = "all"` as the default as it made much more sense about the expected behavior. I changed it to `NULL` because I thought it was strange that the same argument could accept a number (or vector of numbers) to select a subset of slides, but also a character (`"all"`) if you wanted to include all slides. But with `NULL`, the intension is kind of confusing. I think a potential solution might be to keep `NULL` to mean "use all slides" and maybe change the argument name to something like `slide_subset` (there's probably a better name than that, but you get what I mean). That way the value of `NULL` implies that you're not subsetting (i.e. you're using all the slides), and if you set `slide_subset` to a number / vector of numbers, you're saying which subset of slides you want to use. 

I don't have super strong feelings about this...either way it's kind of a tough one to make the intention clear about what this argument does.

**Comment by gadenbuie** [comment]
Sorry @jhelvy I started replying to your comments last night but got distracted by a minor fight with the CI setup (which is now working!)

I had the same hesitation when I came upon the `slides` argument, but I don't think it's worth changing it. I think the primary conceptual conflict is with `input`, but that's so clearly named that I don't think it's an issue. (If you do feel strongly about changing it, I think `slide_number` is a good argument name.)

I'm not worried about mixing character and integer argument values, as long as we have good docs and error messages around the argument, which I think we do now. I also think that `slides = "all"` or `slides = 1` as the default argument makes the `slides` argument name much more understandable than `NULL` as a default. You could read either in the function signature and have a good sense of what the argument does. But `slides = NULL` as a default raises more questions than it answers.

I'm wondering if we should cover other special cases, like `"first"` or `"last"`. The first slide is easy to find with an index of `1`, but the last slide is hard to target unless you know exactly how many slides are in your deck.

```r
build_png("slides.Rmd", "slides_title.png", slides = "first")
build_png("slides.Rmd", "slides_closing.png", slides = "last")
```

Another thought is that we could explicitly support negative integers, e.g. to enable dropping certain slides.

```r
build_mp4("slides.Rmd", slides = -1)
```

**Comment by gadenbuie** [comment]
> You mean an additional action to run like R CMD check on every commit? Something like that could be useful to catch errors.

Yes! And it's running now :tada: Two other big advantages are that it helps when others contribute code and that it also helps you test the package in other environments and R versions than your local machine. I found a bunch of issues where I was using newer features that were added in R 4.0 that I forgot aren't portable to older versions of R.

**Comment by gadenbuie** [comment]
One thing about the CI checking to keep in mind, however, is that because of idiosyncrasies with chromote, it's likely there will be occasional false-negative failures (like in the last test run). If a test is passing in most of the platforms but failing in one, it's probably _fine_.

**Comment by jhelvy** [comment]
Okay, the `first` and `last` thing alone is a good enough reason to keep things the way they are with `slides`. I like that idea, especially for `last`. Negative indexing might also be convenient, and both probably aren't too much more work to support with the way things are now setup.

One more thing, I don't think I added `slides` to `build_social()` - is that somewhere in this PR / do you think it's a good idea?

**Comment by gadenbuie** [comment]
> Okay, the `first` and `last` thing alone is a good enough reason to keep things the way they are with `slides`. I like that idea, especially for `last`. Negative indexing might also be convenient, and both probably aren't too much more work to support with the way things are now setup.

Yeah I think it works nicely now and it wasn't too hard to implement. Using negative indices to drop slides is a nice little addition; I doubt it will be used often but it at least reduces surprises if someone tries it out.

> One more thing, I don't think I added `slides` to `build_social()` - is that somewhere in this PR / do you think it's a good idea?

I could see adding it but `build_social()` is a bit different since it uses `webshot2` instead of the `html -> pdf -> png` solution. Having the social be the first slide is such a good choice that I think we can wait on that.

**Comment by gadenbuie** [comment]
@jhelvy All set for your review!

**Comment by jhelvy** [comment]
Okay, I've gone through and made a few tiny changes, but it looks good to me. Here's a quick summary:

- Bumped the version to 0.0.9, updated DESCRIPTION, CITATION, README 
- Caught a small bug in `build_png()` where if `slides = -1` (or any single-digit negative number) the output wouldn't change to a `.zip` file extension. Fixed this by just moving the update to use `.zip` a little further down in the build process.
- Updated the example slides with another slide about the `slides` argument, and re-built all examples.

Let me know if you want to take another look, otherwise I'll merge this.

**Comment by gadenbuie** [comment]
Looking great! Good catch with `buid_png()` and thank you for the mention in the citation.

One small final detail: do you want to add a badge for the new GHA checks? You can do that with `use_github_actions_badge()`. Along those lines you might also want to disable the Travis checks unless they do something that isn't covered by GitHub Actions. (I think that just means deleting the `.travis.yml`)

Other than that thanks for the review and I think we're ready to merge whenever you want!

**Comment by jhelvy** [comment]
Just removed the `.travis.yml`. 

I tried `usethis::use_github_actions_badge()` but got an error, I think it's because I'm working off of your branch. 
I'll merge this then will try and add the GHA button.

**Comment by jhelvy** [comment]
GHA button is in the README. 

There are so many great additions in this PR - tidied up so many loose ends and made the whole package so much more robust wrt file paths, default settings, etc. I also learned a lot watching these changes. Thanks again for putting in the effort on this!
 
P.S. I added a shout out to xaringan.club in the example slides :)

**Comment by jhelvy** [comment]
P.P.S. Maybe add https://xaringan.gallery/ to the club?

**Pull request merged**
