### PR TITLE
Rc v0.1.0

### PR DESCRIPTION
**Pull request by jhelvy**
This branch includes minor changes in preparation for submitting v0.1.0 of renderthis to CRAN. See #53 for checklist.

### CODE REVIEW

**Comment by jhelvy** [comment]
@gadenbuie I've started trying to get everything prepped to submit v0.1.0 to CRAN. Right now a couple urls are broken because they point to the documentation pages that aren't building in actions. I can't figure out the issue as to why the pages won't build.

**Comment by gadenbuie** [comment]
@jhelvy I updated the pkgdown github action to use the latest actions from r-lib. That seems to have fixed everything on that end.

I also removed the `Remotes` field from the DESCRIPTION so we now depend on the CRAN versions of `chromote`, `webshot2` and `xaringanExtra`... Although I realized in that process that you technically don't need to depend on xaringanExtra after all.

Which brought me to taking a look at the examples folder. Since that's shipped with the package and needs to be kept up to date, I'd recommend that we only include the `examples.R` and `slides.Rmd` files. That gives someone easy access to a set of slides to try out.

To make the examples available broadly, however, we could incorporate them into the pkgdown site and have the pkgdown action rebuild the outputs by running `examples.R` (or a slimmed-down version of that script). I can submit a PR for this.

**Comment by jhelvy** [comment]
That's an excellent idea! I also have some of the example slide outputs in /man/figures/ because I embed some of those file in the README. Perhaps we could also automate them to be built and put in that folder?

**Comment by gadenbuie** [comment]
> I also have some of the example slide outputs in /man/figures/ because I embed some of those file in the README. Perhaps we could also automate them to be built and put in that folder?

Would you be open to us moving some of the README content out of the README and into the pkgdown site? I used to work hard to have a complete README with the same content repeated on the pkgdown site, but I've found that it's not worth the maintenance burden. Especially since assets used in the README inflate the package size because they become part of the package tarball.

I'd recommend the README does basic installation, motivation, outline of functions and then a prominent "read more" link to pkgdown site where it all the rest, in particular the rendered examples. That way, the examples can be rendered all at once in one place.

**Comment by jhelvy** [comment]
That's a better structure - let's do that to simply the readme and remove the slides from the man folder.

**Comment by gadenbuie** [comment]
Okay it should all be done now! See #58 for details — plus a few commits I made on main to fix a few little things. I like the new organization! 

I may have missed references to the example slides/outputs in places other than README, sorry in advance if I did.

**Comment by jhelvy** [comment]
Yeah, very tidy now :)

I'll try to look through it carefully later and will go back through the checklist in #53, then hopefully we can ship it to CRAN soon!

**Comment by jhelvy** [comment]
@gadenbuie I'm about to send this to CRAN. The only note I'm getting is for possible spelling errors in the DESCRIPTION (html, png, etc). Other than that, I'm still getting a R-CMD-check failure on the tests here for windows. Any idea on how to fix that?

**Comment by gadenbuie** [comment]
> I'm still getting a R-CMD-check failure on the tests here for windows.

I don't think these errors will show up on CRAN since they should be skipped on CRAN. That said, it's worth running `devtools::check_win_release()` and `devtools::check_win_oldrelease()` in addition to `devtools::check_win_devel()` (the last one shows up in the checklist).

One other idea would be to include a test file like [the one I added in learnr](https://github.com/rstudio/learnr/blob/main/tests/testthat/test-shinytest2-aaa.R) that seems to resolve these issues. chrome (via chromote) is still a little flaky though, it's not unusual for me to have to re-run jobs occasionally. I remember running into similar problems consistently with Windows and that chromote-warming code is what Barret Schloerke recommended to me.

> The only note I'm getting is for possible spelling errors in the DESCRIPTION (html, png, etc).

I think maybe [rsvg](https://github.com/ropensci/rsvg/) could be a good example here. They say something like "png, gif, html format" in the [DESCRIPTION](https://github.com/ropensci/rsvg/blob/8a773961baf792f669288a9b6234aa1156447281/DESCRIPTION#L12) 

    Renders vector-based svg images into high-quality custom-size
    bitmap arrays using 'librsvg2'. The resulting bitmap can be written to
    e.g. png, jpeg or webp format. In addition, the package can convert
    images directly to various formats such as pdf or postscript.

and then `png`, `webp`, `jpeg`, etc are included in [inst/WORDLIST](https://github.com/ropensci/rsvg/blob/8a773961baf792f669288a9b6234aa1156447281/inst/WORDLIST#L11-L16).

**Comment by jhelvy** [comment]
Ah inst/WORDLIST is what I was looking for. I figured there had to be a way to declare known words and I didn't know about this file. That resolves the note when using `devtools::check()`, but I still get a note about the spelling with `devtools::check_win_release()` and `devtools::check_win_devel()`. Maybe windows ignores the inst/WORDLIST file? Either way I would hope that CRAN would ignore this note given the context.

I'm not getting any other errors on any of the devtools checks, but I do get the same error from the test failures with `rhub::check()`. But I don't think any of these will show up for CRAN. Do you think I should just go ahead and submit?

**Comment by gadenbuie** [comment]
Okay, we've got a green check here and probably everywhere else too! ✅ 🎉 

I think it's okay to submit now, and I think that the note about misspelled words is likely to be a false positive that won't appear on the CRAN incoming checks — I have to imagine they've added `png`, `svg` etc to their spelling dictionary (which turns out to not have the same mechanism as `inst/WORDLIST` which comes from the [spelling package](https://docs.ropensci.org/spelling/index.html)).

I found [this mailing list entry](https://www.mail-archive.com/r-package-devel@r-project.org/msg07149.html) that was helpful, but my takeaway is that it's unlikely to be a problem or it will just result in CRAN asking you to make a change that isn't easy to anticipate from the documentation. You _could if you want_ add a note in the CRAN notes mentioning the flagged words and that they're not actually a problem.

**Comment by jhelvy** [comment]
Yay green checks! 🎉 

Okay, just to be careful I'll add a note in the cran comments file about the spelling note. I'll ship this out shortly!

**Comment by jhelvy** [comment]
Okay, got some quick feedback from CRAN to fix:

- [x] Do not start the description with "This package", package name,
title or "Functions for".
- [x] Please always write package names, software names and API (application
programming interface) names in single quotes in title and description.
e.g: --> 'html',... (This should fix the note about spelling)
- [ ] Please ensure that your functions do not write by default or in your
examples/vignettes/tests in the user's home filespace (including the
package directory and `getwd()`). This is not allowed by CRAN policies.
- [ ] Please omit any default path in writing functions. In your
examples/vignettes/tests you can write to `tempdir()`.

**Comment by gadenbuie** [comment]
> Do not start the description with "This package", package name

Is that in extra checks? If not we should suggest it there.

> Please always write package names, software names and API (application
programming interface) names in single quotes in title and description.
e.g: --> 'html'

I'm all for trying the quotes if that makes CRAN happy but I think this is a false positive matching against HTML (analogous to API) and confusing it with the file extension `.html`. Oh well. 

The tempfile bits are understandable (even if they reduce the readability of exercises). Hopefully they won't be too hard to update.

All in all, a pretty successful first submission! 🎉

**Comment by jhelvy** [comment]
> Is that in extra checks? If not we should suggest it there.

I didn't see it. I'll make a PR in [extrachecks](https://github.com/DavisVaughan/extrachecks) to add it.

I've already fixed the first two simple issues in the DESCRIPTION. Just need to deal with the tempfile stuff and I think we'll be good. Do you want to try and fix those?

**Comment by gadenbuie** [comment]
@jhelvy Did CRAN link to check results or provide any hints about which code was leaving files? One thing that might be problematic is that all of the examples are wrapped in `\dontrun{}` and CRAN usually runs those anyway on first submission. That would be problematic because the examples use `"slides.Rmd"` or something similar, which won't exist unless we do some more work. But it'd be helpful to see the logs in case there are other places where we're not careful enough about temp files (although I'm pretty sure our tests are okay).

**Comment by jhelvy** [comment]
> Did CRAN link to check results or provide any hints about which code was leaving files?

Unfortunately no. The check list I wrote above is the only feedback. Perhaps we could modify the examples to use a tempdir to download the [slides.Rmd file](https://raw.githubusercontent.com/jhelvy/renderthis/main/inst/example/slides.Rmd) from gh and then use that file to render things? It's a bit cumbersome, but it might actually be a better example because it could actually run without erroring.

**Comment by gadenbuie** [comment]
Okay, examples are annoying. I think I came up with a reasonable solution though. I added an internal function (but exported, i.e. documented but won't appear in the pkgdown site) called `with_example()` that makes it a little easier to use the example slides and will definitely clean up after itself since everything happens in a temp dir that's deleted on exit.

I also moved the examples into R scripts in `man/examples/examples_{context}.R` which makes it a little easier to edit and test the examples when writing them. This is something I learned from Alex Rossell Hayes but it's not (yet?) standard practice everywhere (meaning it doesn't appear in the R Packages book).

Let me know what you think!

**Comment by gadenbuie** [comment]
Ran out of time to tinker with this for now but I'm thinking we may end up having to simplify the examples considerably down to a single `to_*()` each.

**Comment by gadenbuie** [comment]
@jhelvy I think I came up with a decent solution, although it's kinda cheating. Basically, I ended up setting up `with_example()` so that it doesn't throw an error and will instead downgrade errors to messages. The fact that CRAN requires that examples can't throw errors, even if the errors are informative and expected is a major limitation; I think this is a reasonable approach in light of the policy. We have plenty of tests around the same behavior, plus we also include the same examples in the Get Started vignette, so I don't think we lose anything. I also cut the examples back to one or two examples per function since they take a while to run.

I think this is ready to go, but I'd recommend another round of checks on winbuilder and r-hub.

**Comment by jhelvy** [comment]
Awesome stuff! Okay I'll run a bunch of checks and will report back here any further edits that might be needed.

**Comment by jhelvy** [comment]
Okay everything seems to check out. The only potential issue is that some of the examples took >5s to run, but only just barely (all between 5-6s). This doesn't show up as a note though, so hopefully that should be okay. Ready to re-submit?

**Comment by gadenbuie** [comment]
> he only potential issue is that some of the examples took >5s to run, but only just barely (all between 5-6s). This doesn't show up as a note though, so hopefully that should be okay.

Yeah, I think so. Most of the examples won't actually run on CRAN since chrome won't be installed (afaik), and those are the long ones.

**Comment by jhelvy** [comment]
Okay, round 2!

**Pull request merged**
