### PR TITLE
Deprecate but provide aliases for all `build_*()` functions

### PR DESCRIPTION
**Pull request by gadenbuie**
Creates alias `build_*()` functions for all of the new `to_*()` functions using `lifecycle::deprecate_warn()` to politely signal that the new function should be used.

I also added deprecations warnings around the argument change from `input` to `from` and `output_file` to `to`.

Some other notes:

- I switched to a more simple workflow for checking the package (check-standard)
- I bumped the version to `0.0.9.9000` for continuity
- I squashed a few complaints from rcmdcheck about not calling any functions in xaringan and another one about vignettes

This should get renderthis into a good place for general consumption again!

### CODE REVIEW

**Comment by jhelvy** [comment]
Btw, I thought the `to_all()` function wasn't necessary in retrospect. Most people probably just want to render one or two things (maybe I'm wrong), and it introduces some complications. For example, you might want your pdf to have incremental slides, but you might not want the increments for your gif or pngs you share on twitter. In the end, it just seemed like a function trying to do too much, so I felt we should drop it. I'm fine either way.

**Comment by gadenbuie** [comment]
> In the end, it just seemed like a function trying to do too much, so I felt we should drop it. I'm fine either way.

Yeah that's a good point. I wonder if we could find a good compromise that makes it easier to pipe from one `to_*()` function to another so you could chain together your steps.

For now I think we should undo the changes I made to rename `build_all()` and then leave `build_all()` as-is but mark it as deprecated. We can explore the pipe-compatibility idea in another issue/PR.

**Comment by jhelvy** [comment]
Okay I think this is ready to go. I made a couple small additions:

- I removed any reference to qmd files as they're actually not yet supported. This is another feature we should add though as I expect Quarto slides will become popular. Obviously Quarto slides that are already rendered to html can then be used for any other `to_*()` functions.
- I updated the example slides (some of the outputs still had {xaringanBuilder} in the name).
- I bumped the version to 0.1.0.

**Comment by gadenbuie** [comment]
This looks great, except that I'd recommend holding off on bumping the version to 0.1.0 until you send it to CRAN. There are a few more things to do, housekeeping kinds of things that come up in the process and you'll want to leave yourself some room to differentiate between the dev version leading up to submitting and the one you submitted.

Typically, I'll do as much as possible in the main branch and then just before submitting I'll use `usethis::use_release_issue("0.1.0")` to open an issue and I'll move the final details into a PR with a branch name like `rc-v0.1.0`. Then I'll push the final fixes and last minute things I find to that branch. And when CRAN asks for changes I can make them in the PR branch and when CRAN accepts, I merge the PR.

I _wouldn't_ recommend making this branch the release candidate branch since our current main branch is in a little bit of a weird state. It'd be nice to merge this branch soonish so that renderthis installs and works correctly for people finding the package now.

**Comment by jhelvy** [comment]
This is all makes perfect sense. I've never followed that too carefully of a workflow with submitting to CRAN, so this is a good learning exercise for me. Do you want to reset the version number and then say this branch is good to merge?

**Comment by gadenbuie** [comment]
Cool, I just rolled back the version bump so this should be good to go! I'd say I'm overly careful with releasing to CRAN but also I don't know what I'd do without the checklist in `usethis::use_release_issue()` 😃

**Comment by jhelvy** [comment]
Just going to say I'm so glad you told me about `usethis::use_release_issue()`. I just used it to release another package ([logitr](https://github.com/jhelvy/logitr)) to CRAN and omg it was sooooo much better than my hacky checks I used to do. Now just have to wait to see if it's accepted.

{usethis} is truly a magical package 🥇

**Pull request merged**
